yaml

name: Secure Fetch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script with secret
        run: |
          node -e "const token = process.env.GITHUB_TOKEN; // Access the secret
          fetch('https://api.github.com/user', {
            headers: {
              Authorization: `token ${token}`
            }
          }).then(res => res.json()).then(data => console.log(data));"
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }} #   Replace MY_PAT with your secret name.
